### ISSUE TITLE
.log.sensi API汇总

### ISSUE THREAD

**Issue by u21h2** [godspeedcurry/godscan#2]
.log.sensi文件能不能汇总下所有提取到的API

**Comment by godspeedcurry** [comment]
搞定了，提供了两个文件：
api去重版在：`日期/ip_port/spider.log.api.unique`，
完整路径+api在：`日期/ip_port/spider.log.api.unique.path`，后续建议手工配合dirbrute模块扫所有api
期望发现的结果形如:
* xxx/yyy/.git
* xxx/yyy/..;/..;/actuator
